create schema if not exists test;

/* H2 doesn't support "ON UPDATE" */

CREATE TABLE IF NOT EXISTS `player`  (
  `Uin` BIGINT NOT NULL,
  `SUin` varchar(32) NOT NULL DEFAULT '',
  `Uuid` VARCHAR(128) NOT NULL DEFAULT '',
  `platform` tinyint NOT NULL DEFAULT 0 ,
  `channel` int NOT NULL DEFAULT 0 ,
  `serverid` smallint NOT NULL DEFAULT 0 ,
  `os` smallint NOT NULL DEFAULT 0 ,
  `device` varchar(128)  not null default '' ,
  `osVersion` int  not null default 0 ,
  `AccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `AccountName` VARCHAR(128) NOT NULL DEFAULT '',
  `NickName` VARCHAR(64) NOT NULL DEFAULT '',
  `Sex` tinyint NOT NULL DEFAULT 0 ,
  `Vip` tinyINT NOT NULL DEFAULT 0 ,
  `Level` smallint NOT NULL DEFAULT 0 ,
  `Exp` INT NOT NULL DEFAULT 0 ,
  `Energy` smallINT NOT NULL DEFAULT 0 ,
  `Energy_Time` timestamp NOT NULL DEFAULT now(),
  `Coin` INT NOT NULL DEFAULT 0,
  `Gem` INT NOT NULL DEFAULT 0,
  `TotalGem` INT NOT NULL DEFAULT 0 ,
  `RMB`  int not null default 0   ,
  `friendvalue` INT NOT NULL DEFAULT 0 ,
  `createtime` timestamp NOT NULL DEFAULT now() ,
  `lastlogintime` timestamp NOT NULL DEFAULT now() ,
  `lastActivetime` timestamp NOT NULL DEFAULT now(),
  `Honor` int not null default 0 ,
  `PVPEnergy`  tinyint not null default 0 ,
  `PVPEnergyTime`  timestamp not null default now() ,
  `PVPValue`  int not null default 0 ,
  PRIMARY KEY (`Uin`),
  Key idx_level (`level`),
  Key idx_nickname (`NickName`),
  Key idx_lastlogintime (`lastlogintime`),
  UNIQUE KEY idx_account(`AccountId`,`AccountName`,`channel`,`serverid`))
   ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `pay_order` (
    `uin` BIGINT NOT NULL,
    `account_id` varchar(128) NOT NULL ,
    `user_level` smallINT DEFAULT 0,
    `vip_level` tinyINT DEFAULT 0,
    `order_id` varchar(128) NOT NULL,
    `product_id` VARCHAR(20) NOT NULL,
    `product_name` VARCHAR(20) NOT NULL,
    `product_desc` VARCHAR(50) NOT NULL,
    `money` INT DEFAULT 0,
    `channel` INT DEFAULT 0,
    `serverId` smallint DEFAULT 0,
    `create_time` timestamp DEFAULT 0,
    `status` tinyint DEFAULT 0,
    `order_type`  tinyint not null default 0,
    `receipt_data`  varchar(10240) not null default '',
    PRIMARY KEY (`uin`,`order_id`,`channel`))ENGINE = InnoDB DEFAULT CHARSET=utf8;
